# Generated by Django 4.0.5 on 2022-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
